import { Product, Category } from './types';

export const BANK_INFO = {
  bank: 'Banco Aliado',
  name: 'Nathalie Levy',
  accountType: 'Cuenta Ahorros',
  accountNumber: '1040071392',
};

export const CREDIT_CARD_SURCHARGE = 0.05;

export const CONTACT = {
  whatsapp: '50766712588',
  phone: '(+507) 6433-2724',
  email: 'playtimekids@gmail.com',
  instagram: '@playtimekids',
};

export const CATEGORIES: { id: Category; label: string; icon: string; description: string }[] = [
  { id: 'planes', label: 'Planes', icon: '🎉', description: 'Paquetes completos para tu fiesta' },
  { id: 'belleza', label: 'Belleza', icon: '💅', description: 'Maquillaje, manicure, peinados y spa' },
  { id: 'entretenimiento', label: 'Entretenimiento', icon: '🎭', description: 'Títeres, animación y personajes' },
  { id: 'snacks', label: 'Snacks', icon: '🍿', description: 'Máquinas de algodón, raspado, popcorn' },
  { id: 'gymboree', label: 'Gymboree', icon: '🏰', description: 'Sets de gymboree completos' },
  { id: 'inflables', label: 'Inflables', icon: '🎪', description: 'Bounce houses y toboganes' },
  { id: 'piscinas', label: 'Piscinas', icon: '🔵', description: 'Piscinas de pelotas y túneles' },
  { id: 'alquiler', label: 'Alquiler', icon: '🎈', description: 'Equipos individuales y accesorios' },
  { id: 'servicios', label: 'Servicios', icon: '🎵', description: 'Música, transporte y extras' },
];

export const PRODUCTS: Product[] = [
  // ═══ PLANES ═══
  {
    id: 'plan-1',
    name: 'Plan #1 - Completo',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), actividad de arte (3 atriles con 30 dibujos), alquiler de equipos (caballitos, piscina de bolas, túnel, mini parque y pads de piso). 2 teachers. Duración: 3 horas.',
    price: 500,
    image: '/images/products/plan-1.jpg',
    featured: true,
  },
  {
    id: 'plan-2',
    name: 'Plan #2 - Show + Equipos',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), alquiler de equipos (caballitos, piscina de bolas, túnel, mini parque y pads de piso). 2 teachers. Duración: 3 horas.',
    price: 380,
    image: '/images/products/plan-2.jpg',
    featured: true,
  },
  {
    id: 'plan-3',
    name: 'Plan #3 - Show + Arte',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), actividad de arte (3 atriles con 30 dibujos). 2 teachers. Duración: 3 horas.',
    price: 260,
    image: '/images/products/plan-3.jpg',
  },
  {
    id: 'plan-4',
    name: 'Plan #4 - Show de Títeres',
    category: 'planes',
    description: 'Show de Títeres con Lala. 2 teachers. Duración del show: 45 min.',
    price: 225,
    image: '/images/products/plan-4.jpg',
  },
  {
    id: 'plan-5',
    name: 'Plan #5 - Animación y Sorpresas',
    category: 'planes',
    description: 'Animación por 1 hora con juegos y competencia.',
    price: 250,
    image: '/images/products/plan-5.jpg',
  },
  {
    id: 'plan-5-personaje',
    name: 'Plan #5 Extra - Personaje con Animación',
    category: 'planes',
    description: 'Personaje con animación completa.',
    price: 380,
  },
  {
    id: 'plan-12',
    name: 'Plan #12 - Cumpleaños Mommy & Me',
    category: 'planes',
    description: 'Celebra junto a tus amigas y sus hijos. Actividades de motricidad fina y gruesa, sensoriales, musicales, mini show de títeres y transporte. 15 niños. 3 teachers. Duración: 3 horas.',
    price: 450,
    image: '/images/products/plan-12.jpg',
  },

  // ═══ BELLEZA ═══
  {
    id: 'plan-6-makeup',
    name: 'Plan #6 - Makeup / Pintacarita Birthday',
    category: 'belleza',
    description: 'Kit completo de maleta de maquillaje con espejo y luz. 1 teacher. Duración: 2 horas. Extras: Maquillaje Deluxe con brillantes ($10), Facial ($10), Teacher extra ($80).',
    price: 120,
    image: '/images/products/plan-6.jpg',
    featured: true,
  },
  {
    id: 'plan-7-manicure',
    name: 'Plan #7 - Princess Manicure',
    category: 'belleza',
    description: 'Mesa de madera, alfombra, 4 sillas Tiffany, decoración de mesa. Pintura de uñas y sticker. 1 teacher. Duración: 2 horas. Extra teacher ($80).',
    price: 100,
    image: '/images/products/plan-7.jpg',
  },
  {
    id: 'plan-9-hair',
    name: 'Plan #9 - Hair Glamour',
    category: 'belleza',
    description: 'Peinado con trenzas de colores y todo su kit, coronitas para princesas, kit completo de maleta de peinado con espejo y luz, silla alta. 1 teacher. Duración: 2 horas. Extras: Teacher extra ($80), extensiones ($50).',
    price: 140,
    image: '/images/products/plan-9.jpg',
  },
  {
    id: 'plan-10-spa',
    name: 'Plan #10 - Home Beauty & Spa',
    category: 'belleza',
    description: '1.5 horas de belleza y diversión. Peinado y maquillaje especial para cumpleañera, manicure express, 3 pedicure spa, peinado con coronita. 2 mesas, 6 sillas Tiffany, alfombras, decoración. 15 niñas máximo. 3 teachers.',
    price: 400,
    image: '/images/products/plan-10.jpg',
    featured: true,
  },
  {
    id: 'plan-11-princess',
    name: 'Plan #11 - Princess Birthday',
    category: 'belleza',
    description: 'Niñas ilimitadas. Animación con modelaje y baile, música, pink carpet, peinado con extensiones y coronitas, manicure deluxe, pedicure spa, masaje facial, tarima para modelaje, carpa de decoración, maquillaje especial para cumpleañera. 5 teachers. Duración: 3 horas.',
    price: 700,
    image: '/images/products/plan-11.jpg',
    featured: true,
  },

  // ═══ ENTRETENIMIENTO ═══
  {
    id: 'show-titeres',
    name: 'Show de Títeres con Lala',
    category: 'entretenimiento',
    description: 'Show de títeres interactivo con Lala. Duración: 45 minutos.',
    price: 225,
  },
  {
    id: 'animacion',
    name: 'Animación 1 Hora',
    category: 'entretenimiento',
    description: 'Animación por 1 hora con juegos y competencias.',
    price: 250,
  },
  {
    id: 'personaje-animacion',
    name: 'Personaje con Animación',
    category: 'entretenimiento',
    description: 'Animación con personajes temáticos. Preguntar por personaje de su interés.',
    price: 380,
    image: '/images/products/personajes.jpg',
  },
  {
    id: 'personaje-fotos',
    name: 'Personaje 1 Hora (Saludos y Fotos)',
    category: 'entretenimiento',
    description: 'Personaje temático por 1 hora para saludos y fotos. Preguntar por personaje de su interés.',
    price: 150,
    image: '/images/products/personajes.jpg',
  },
  {
    id: 'manualidades',
    name: 'Manualidades según Tema y Edad',
    category: 'entretenimiento',
    description: '3 atriles con crayola y 15 dibujos. Pueden pintar 6 niños a la vez. Consulta nuestro catálogo de manualidades.',
    price: 0,
  },

  // ═══ SNACKS ═══
  {
    id: 'algodon-azucar',
    name: 'Algodón de Azúcar',
    category: 'snacks',
    description: 'Máquina de algodón de azúcar. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 100,
    image: '/images/products/snacks-1.jpg',
  },
  {
    id: 'algodon-automatico',
    name: 'Algodón de Azúcar (Máquina Automática)',
    category: 'snacks',
    description: 'Máquina automática de algodón de azúcar. Personal y materiales incluidos. Duración: 3 horas.',
    price: 140,
    image: '/images/products/snacks-auto.jpg',
  },
  {
    id: 'raspado',
    name: 'Raspado',
    category: 'snacks',
    description: 'Máquina de raspado. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 130,
    image: '/images/products/snacks-1.jpg',
  },
  {
    id: 'popcorn',
    name: 'Pop Corn',
    category: 'snacks',
    description: 'Máquina de palomitas. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 100,
    image: '/images/products/snacks-2.jpg',
  },
  {
    id: 'slushy',
    name: 'Slushy',
    category: 'snacks',
    description: 'Máquina de slushy. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 130,
    image: '/images/products/snacks-2.jpg',
  },

  // ═══ GYMBOREE ═══
  {
    id: 'gymboree-blanco-grande',
    name: 'Gymboree Blanco Grande',
    category: 'gymboree',
    description: 'Cerca blanca, pads de piso, carritos foam blanco, mini parque, túnel gym redondo, lego foam, roller coaster blanco, piscina blanca.',
    price: 250,
    image: '/images/products/gymboree-blanco-grande.jpg',
    featured: true,
  },
  {
    id: 'gymboree-blanco-chico',
    name: 'Gymboree Blanco Chico',
    category: 'gymboree',
    description: 'Cerca blanca, pads de piso, piscina blanca, túnel de gym, carritos foam blanco, lego foam, mini parque.',
    price: 160,
    image: '/images/products/gymboree-blanco-chico.jpg',
  },
  {
    id: 'gymboree-rosado-grande',
    name: 'Gymboree Rosado Grande',
    category: 'gymboree',
    description: 'Cerca rosada, pads rosado, caballito rosado, mini parque, puente rosado, piscina de flor con bolas rosadas, lego foam rosado, túnel gym rosado, caballitos saltarín rosado, roller coaster rosado.',
    price: 290,
    image: '/images/products/gymboree-rosado-grande.jpg',
  },
  {
    id: 'gymboree-nina-mixto',
    name: 'Gymboree Niña Mixto',
    category: 'gymboree',
    description: 'Cerca rosada, pads blanco, caballito rosado, piscina de flor con bolas blancas, roller coaster rosado, túnel gym blanco, puente rosado, mini parque rosado, lego foam mixto.',
    price: 285,
    image: '/images/products/gymboree-nina-mixto.jpg',
  },
  {
    id: 'gymboree-rosado-chico',
    name: 'Gymboree Rosado Chico',
    category: 'gymboree',
    description: 'Cerca rosada, pads rosado, caballito rosado, mini parque, puente rosado, piscina redonda rosada, lego foam rosado.',
    price: 180,
    image: '/images/products/gymboree-rosado-chico.jpg',
  },
  {
    id: 'set-colchoneta-escalera',
    name: 'Set Colchoneta Escalera',
    category: 'gymboree',
    description: 'Set de colchoneta con escalera para actividades motrices.',
    price: 220,
    image: '/images/products/gymboree-blanco-grande.jpg',
  },

  // ═══ INFLABLES ═══
  {
    id: 'bubble-house',
    name: 'Bubble House',
    category: 'inflables',
    description: '3 metros la bola x 1.80 metros túnel.',
    price: 190,
    image: '/images/products/bubble-house.jpg',
  },
  {
    id: 'bounce-house-blanco',
    name: 'Bounce House Blanco',
    category: 'inflables',
    description: 'Sin decoración. Dimensiones: 3.50W x 3.50L x 3.96H metros.',
    price: 120,
    image: '/images/products/bounce-house.jpg',
  },
  {
    id: 'inflable-grande-1',
    name: 'Inflable Grande con Tobogán',
    category: 'inflables',
    description: 'Dimensiones: 5.4 x 5 x 4 metros.',
    price: 170,
    image: '/images/products/inflable-grande-1.jpg',
  },
  {
    id: 'inflable-mediano',
    name: 'Inflable Mediano',
    category: 'inflables',
    description: 'Dimensiones: 4.4 x 4 x 3.8 metros.',
    price: 140,
    image: '/images/products/inflable-mediano.jpg',
  },
  {
    id: 'inflable-grande-2',
    name: 'Inflable Grande',
    category: 'inflables',
    description: 'Dimensiones: 5.5 x 4.5 metros.',
    price: 170,
    image: '/images/products/inflable-grande-2.jpg',
  },
  {
    id: 'inflable-chico',
    name: 'Inflable Pequeño',
    category: 'inflables',
    description: 'Dimensiones: 3L x 3W x 2.75H metros.',
    price: 110,
    image: '/images/products/inflable-chico.jpg',
  },
  {
    id: 'inflable-mini-1',
    name: 'Inflable Mini (2.7m)',
    category: 'inflables',
    description: 'Dimensiones: 2.7 x 2.2 x 2.0 metros.',
    price: 90,
    image: '/images/products/inflable-mini.jpg',
  },
  {
    id: 'inflable-mini-2',
    name: 'Inflable Mini (2.5m)',
    category: 'inflables',
    description: 'Dimensiones: 2.5 x 2.5 metros.',
    price: 90,
    image: '/images/products/inflable-mini.jpg',
  },

  // ═══ PISCINAS Y TÚNELES ═══
  {
    id: 'piscina-cuadrada-blanca',
    name: 'Piscina Cuadrada Blanca de Foam',
    category: 'piscinas',
    description: 'Colores a escoger: blanco, rosado, azul, negro. Dimensiones: 72 x 72 pulgadas.',
    price: 88,
    image: '/images/products/piscina-cuadrada.jpg',
  },
  {
    id: 'piscina-colores-60',
    name: 'Piscina con Colores (60")',
    category: 'piscinas',
    description: 'Dimensiones: 60 x 60 pulgadas. Varios colores disponibles.',
    price: 60,
    image: '/images/products/piscina-colores.jpg',
  },
  {
    id: 'piscina-redonda-grande',
    name: 'Piscina Redonda Grande',
    category: 'piscinas',
    description: '3 metros de diámetro.',
    price: 100,
    image: '/images/products/piscina-redonda.jpg',
  },
  {
    id: 'piscina-redonda-chica',
    name: 'Piscina Redonda Pequeña',
    category: 'piscinas',
    description: '1.5 metros de diámetro.',
    price: 40,
    image: '/images/products/piscina-redonda.jpg',
  },
  {
    id: 'piscina-peces',
    name: 'Piscina de Peces',
    category: 'piscinas',
    description: '1.3 metro de diámetro.',
    price: 85,
    image: '/images/products/piscina-peces.jpg',
  },
  {
    id: 'tunel-grande',
    name: 'Túnel Grande',
    category: 'piscinas',
    description: 'Dimensiones: 215 x 75 x 100 cm.',
    price: 50,
    image: '/images/products/tuneles.jpg',
  },
  {
    id: 'tunel-chico',
    name: 'Túnel Pequeño',
    category: 'piscinas',
    description: 'Dimensiones: 1.50 x 0.70 x 0.50 metros.',
    price: 45,
    image: '/images/products/tuneles.jpg',
  },
  {
    id: 'tunel-largo',
    name: 'Túnel Largo',
    category: 'piscinas',
    description: 'Disponible en blanco y rosado. Dimensiones: 4.26 metros de largo.',
    price: 40,
    image: '/images/products/tuneles.jpg',
  },

  // ═══ ALQUILER INDIVIDUAL ═══
  {
    id: 'surraderos-arco',
    name: '2 Surraderos y Arco',
    category: 'alquiler',
    description: '2 surraderos y arco. No incluye piscina.',
    price: 100,
    image: '/images/products/surraderos.jpg',
  },
  {
    id: 'surradero-sencillo',
    name: 'Surradero Sencillo para Piscina',
    category: 'alquiler',
    description: 'Surradero sencillo para piscina.',
    price: 50,
    image: '/images/products/surraderos.jpg',
  },
  {
    id: 'mini-parque',
    name: 'Mini Parque',
    category: 'alquiler',
    description: 'Mini parque blanco (70.7 x 57") o rosado (59 x 46 x 47").',
    price: 50,
    image: '/images/products/mini-parque.jpg',
  },
  {
    id: 'pads-piso',
    name: 'Pads de Piso',
    category: 'alquiler',
    description: 'Disponible en blanco, turquesa y rosado. Dimensiones: 5 x 5 metros.',
    price: 50,
  },
  {
    id: 'bumper-cars',
    name: 'Bumper Cars (4 carritos)',
    category: 'alquiler',
    description: 'Incluye pads, pista y 4 carritos por 3 horas con personal.',
    price: 250,
    image: '/images/products/bumper-cars.jpg',
    featured: true,
  },
  {
    id: 'racing-cars',
    name: 'Racing Cars',
    category: 'alquiler',
    description: 'Carritos de carrera para niños.',
    price: 75,
    image: '/images/products/racing-cars.jpg',
  },
  {
    id: 'caballito-saltarin',
    name: 'Caballito Saltarín',
    category: 'alquiler',
    description: 'Caballito saltarín individual.',
    price: 50,
  },
  {
    id: 'silla-bebe',
    name: 'Silla para Bebé',
    category: 'alquiler',
    description: 'Silla individual para bebé.',
    price: 2,
    maxQuantity: 20,
  },
  {
    id: 'silla-tiffany',
    name: 'Silla Tiffany',
    category: 'alquiler',
    description: 'Silla Tiffany individual.',
    price: 3,
    maxQuantity: 20,
  },
  {
    id: 'mesa-ninos',
    name: 'Mesa para Niños',
    category: 'alquiler',
    description: 'Mesa individual para niños.',
    price: 15,
    maxQuantity: 10,
  },
  {
    id: 'mesa-madera',
    name: 'Mesa de Madera',
    category: 'alquiler',
    description: 'Mesa de madera individual.',
    price: 25,
    maxQuantity: 10,
  },
  {
    id: 'lego-foam',
    name: 'Lego Foam (set)',
    category: 'alquiler',
    description: 'Set de legos de foam.',
    price: 15,
  },
  {
    id: 'roller-coaster',
    name: 'Roller Coaster',
    category: 'alquiler',
    description: 'Roller coaster individual. Disponible en blanco y rosado.',
    price: 25,
  },
  {
    id: 'cerca',
    name: 'Cerca',
    category: 'alquiler',
    description: 'Cerca individual. Disponible en blanco y rosado.',
    price: 15,
  },
  {
    id: 'palo-pinata',
    name: 'Palo de Piñata',
    category: 'alquiler',
    description: 'Palo de piñata (no incluye piñata).',
    price: 20,
  },
  {
    id: 'silla-cubo-10',
    name: 'Silla / Cubo',
    category: 'alquiler',
    description: 'Silla o cubo individual.',
    price: 10,
    maxQuantity: 20,
  },

  // ═══ SERVICIOS ═══
  {
    id: 'musica',
    name: 'Música durante el Cumpleaños',
    category: 'servicios',
    description: 'Música durante todo el evento. Duración: 3 horas.',
    price: 90,
  },
  {
    id: 'transporte',
    name: 'Transporte',
    category: 'servicios',
    description: 'Montaje y transporte ida y vuelta. Varía según ubicación.',
    price: 50,
  },
  {
    id: 'teacher-extra',
    name: 'Teacher Extra',
    category: 'servicios',
    description: 'Teacher adicional para apoyar en las actividades.',
    price: 80,
    maxQuantity: 5,
  },
  {
    id: 'animacion-modelaje',
    name: 'Animación con Modelaje y Baile',
    category: 'servicios',
    description: 'Animación con modelaje y baile (extra para planes de belleza).',
    price: 65,
  },
  {
    id: 'extra-nina-spa',
    name: 'Extra Niña (Spa)',
    category: 'servicios',
    description: 'Niña adicional para planes de belleza/spa.',
    price: 10,
    maxQuantity: 15,
  },
  {
    id: 'peinado-deluxe',
    name: 'Peinado Deluxe (Extensiones)',
    category: 'servicios',
    description: 'Peinado deluxe con extensiones de colores.',
    price: 25,
    maxQuantity: 15,
  },
  {
    id: 'maquillaje-deluxe',
    name: 'Maquillaje Deluxe (Brillantes)',
    category: 'servicios',
    description: 'Maquillaje deluxe con brillantes.',
    price: 10,
    maxQuantity: 15,
  },
  {
    id: 'facial',
    name: 'Facial',
    category: 'servicios',
    description: 'Tratamiento facial para niñas.',
    price: 10,
    maxQuantity: 15,
  },
];
