import { Product, Category } from './types';

export const BANK_INFO = {
  bank: 'Banco Aliado',
  name: 'Nathalie Levy',
  accountType: 'Cuenta Ahorros',
  accountNumber: '1040071392',
};

export const CREDIT_CARD_SURCHARGE = 0.05;

export const CONTACT = {
  whatsapp: '50764332724',
  phone: '(+507) 6433-2724',
  email: 'playtimekidspty@gmail.com',
  instagram: '@playtimekids',
};

export const CATEGORIES: { id: Category; label: string; icon: string; description: string; subtitle?: string }[] = [
  { id: 'planes', label: 'Planes', icon: '\uD83C\uDF89', description: 'Paquetes completos para tu fiesta' },
  { id: 'belleza', label: 'Spa', icon: '\uD83D\uDC85', description: 'Maquillaje, manicure, peinados y spa', subtitle: 'Maquillaje/pinta carita, glitter bar, peinado, manicure' },
  { id: 'entretenimiento', label: 'Entretenimiento', icon: '\uD83C\uDFAD', description: 'T\u00edteres, animaci\u00f3n y personajes' },
  { id: 'snacks', label: 'Snacks', icon: '\uD83C\uDF7F', description: 'M\u00e1quinas de algod\u00f3n, raspado, popcorn', subtitle: 'M\u00e1quinas algod\u00f3n, raspado, slushy y popcorn' },
  { id: 'gymboree', label: 'Gymboree', icon: '\uD83C\uDFF0', description: 'Sets de gymboree completos' },
  { id: 'inflables', label: 'Inflables', icon: '\uD83C\uDFAA', description: 'Bounce houses y toboganes', subtitle: 'Tama\u00f1os y colores llenos de diversi\u00f3n' },
  { id: 'piscinas', label: 'Piscinas', icon: '\uD83D\uDD35', description: 'Piscinas de pelotas y t\u00faneles' },
  { id: 'alquiler', label: 'Alquiler', icon: '\uD83C\uDF88', description: 'Equipos individuales y accesorios' },
  { id: 'servicios', label: 'Servicios', icon: '\uD83C\uDFB5', description: 'M\u00fasica, transporte y extras' },
  { id: 'manualidades', label: 'Manualidades', icon: '\uD83C\uDFA8', description: 'Actividades creativas para tu fiesta' },
];

export const PRODUCTS: Product[] = [
  // ═══ PLANES ═══
  {
    id: 'plan-1',
    name: 'Plan #1 - Completo',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), actividad de arte (3 atriles con 30 dibujos), alquiler de equipos (caballitos, piscina de bolas, túnel, mini parque y pads de piso). 2 teachers. Duración: 3 horas.',
    price: 500,
    image: '/images/products/plan-1.png',
    featured: true,
  },
  {
    id: 'plan-2',
    name: 'Plan #2 - Show + Equipos',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), alquiler de equipos (caballitos, piscina de bolas, túnel, mini parque y pads de piso). 2 teachers. Duración: 3 horas.',
    price: 380,
    image: '/images/products/plan-2.png',
    featured: true,
  },
  {
    id: 'plan-3',
    name: 'Plan #3 - Show + Arte',
    category: 'planes',
    description: 'Show de Títeres con Lala (45 min), actividad de arte (3 atriles con 30 dibujos). 2 teachers. Duración: 3 horas.',
    price: 260,
    image: '/images/products/plan-3.png',
  },
  {
    id: 'plan-12',
    name: 'Plan #12 - Cumpleaños Mommy & Me',
    category: 'planes',
    description: 'Celebra junto a tus amigas y sus hijos. Actividades de motricidad fina y gruesa, sensoriales, musicales, mini show de títeres y transporte. 15 niños. 3 teachers. Duración: 3 horas.',
    price: 450,
    image: '/images/products/plan-12.png',
  },

  // ═══ BELLEZA ═══
  {
    id: 'plan-6-makeup',
    name: 'Plan #6 - Makeup / Pintacarita Birthday',
    category: 'belleza',
    description: 'Kit completo de maleta de maquillaje con espejo y luz. 1 teacher. Duración: 2 horas. Extras: Maquillaje Deluxe con brillantes ($10), Facial ($10), Teacher extra ($80).',
    price: 120,
    image: '/images/products/plan-6-makeup.png',
    featured: true,
  },
  {
    id: 'plan-7-manicure',
    name: 'Plan #7 - Princess Manicure',
    category: 'belleza',
    description: 'Mesa de madera, alfombra, 4 sillas Tiffany, decoración de mesa. Pintura de uñas y sticker. 1 teacher. Duración: 2 horas. Extra teacher ($80).',
    price: 100,
    image: '/images/products/plan-7-manicure.png',
  },
  {
    id: 'plan-9-hair',
    name: 'Plan #9 - Hair Glamour',
    category: 'belleza',
    description: 'Peinado con trenzas de colores y todo su kit, coronitas para princesas, kit completo de maleta de peinado con espejo y luz, silla alta. 1 teacher. Duración: 2 horas. Extras: Teacher extra ($80), extensiones ($50).',
    price: 140,
    image: '/images/products/plan-9-hair.png',
  },
  {
    id: 'plan-10-spa',
    name: 'Plan #10 - Home Beauty & Spa',
    category: 'belleza',
    description: '1.5 horas de belleza y diversión. Peinado y maquillaje especial para cumpleañera, manicure express, 3 pedicure spa, peinado con coronita. 2 mesas, 6 sillas Tiffany, alfombras, decoración. 15 niñas máximo. 3 teachers.',
    price: 400,
    image: '/images/products/plan-10-spa.png',
    featured: true,
  },
  {
    id: 'plan-11-princess',
    name: 'Plan #11 - Princess Birthday',
    category: 'belleza',
    description: 'Niñas ilimitadas. Animación con modelaje y baile, música, pink carpet, peinado con extensiones y coronitas, manicure deluxe, pedicure spa, masaje facial, tarima para modelaje, carpa de decoración, maquillaje especial para cumpleañera. 5 teachers. Duración: 3 horas.',
    price: 700,
    image: '/images/products/plan-11-princess.png',
    featured: true,
  },

  // ═══ ENTRETENIMIENTO ═══
  {
    id: 'show-titeres',
    name: 'Show de Títeres con Lala',
    category: 'entretenimiento',
    description: 'Show de títeres interactivo con Lala. Duración: 45 minutos.',
    price: 225,
  },
  {
    id: 'animacion',
    name: 'Animación 1 Hora',
    category: 'entretenimiento',
    description: 'Animación por 1 hora con juegos y competencias.',
    price: 250,
  },
  {
    id: 'personaje-animacion',
    name: 'Personaje con Animación',
    category: 'entretenimiento',
    description: 'Animación con personajes temáticos. Preguntar por personaje de su interés.',
    price: 380,
    image: '/images/products/personaje-animacion.png',
  },
  {
    id: 'personaje-fotos',
    name: 'Personaje 1 Hora (Saludos y Fotos)',
    category: 'entretenimiento',
    description: 'Personaje temático por 1 hora para saludos y fotos. Preguntar por personaje de su interés.',
    price: 150,
    image: '/images/products/personaje-animacion.png',
  },
  // ═══ SNACKS ═══
  {
    id: 'algodon-azucar',
    name: 'Algodón de Azúcar',
    category: 'snacks',
    description: 'Máquina de algodón de azúcar. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 100,
    image: '/images/products/algodon-azucar.png',
  },
  {
    id: 'algodon-automatico',
    name: 'Algodón de Azúcar (Máquina Automática)',
    category: 'snacks',
    description: 'Máquina automática de algodón de azúcar. Personal y materiales incluidos. Duración: 3 horas.',
    price: 140,
    image: '/images/products/snacks-auto.jpg',
  },
  {
    id: 'raspado',
    name: 'Raspado',
    category: 'snacks',
    description: 'Máquina de raspado. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 130,
    image: '/images/products/algodon-azucar.png',
  },
  {
    id: 'popcorn',
    name: 'Pop Corn',
    category: 'snacks',
    description: 'Máquina de palomitas. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 100,
    image: '/images/products/popcorn.png',
  },
  {
    id: 'slushy',
    name: 'Slushy',
    category: 'snacks',
    description: 'Máquina de slushy. 100% Kosher. Personal y materiales incluidos. Duración: 3 horas.',
    price: 130,
    image: '/images/products/popcorn.png',
  },

  // ═══ GYMBOREE ═══
  {
    id: 'gymboree-blanco-grande',
    name: 'Gymboree Blanco Grande',
    category: 'gymboree',
    description: 'Cerca blanca, pads de piso, carritos foam blanco, mini parque, túnel gym redondo, lego foam, roller coaster blanco, piscina blanca.',
    price: 250,
    image: '/images/products/gymboree-blanco-grande.png',
    featured: true,
  },
  {
    id: 'gymboree-blanco-chico',
    name: 'Gymboree Blanco Chico',
    category: 'gymboree',
    description: 'Cerca blanca, pads de piso, piscina blanca, túnel de gym, carritos foam blanco, lego foam, mini parque.',
    price: 160,
    image: '/images/products/gymboree-blanco-chico.png',
  },
  {
    id: 'gymboree-rosado-grande',
    name: 'Gymboree Rosado Grande',
    category: 'gymboree',
    description: 'Cerca rosada, pads rosado, caballito rosado, mini parque, puente rosado, piscina de flor con bolas rosadas, lego foam rosado, túnel gym rosado, caballitos saltarín rosado, roller coaster rosado.',
    price: 290,
    image: '/images/products/gymboree-blanco-grande.png',
  },
  {
    id: 'gymboree-nina-mixto',
    name: 'Gymboree Niña Mixto',
    category: 'gymboree',
    description: 'Cerca rosada, pads blanco, caballito rosado, piscina de flor con bolas blancas, roller coaster rosado, túnel gym blanco, puente rosado, mini parque rosado, lego foam mixto.',
    price: 285,
    image: '/images/products/gymboree-nina-mixto.png',
  },
  {
    id: 'gymboree-rosado-chico',
    name: 'Gymboree Rosado Chico',
    category: 'gymboree',
    description: 'Cerca rosada, pads rosado, caballito rosado, mini parque, puente rosado, piscina redonda rosada, lego foam rosado.',
    price: 180,
    image: '/images/products/gymboree-rosado-chico.png',
  },
  {
    id: 'set-colchoneta-escalera',
    name: 'Set Colchoneta Escalera',
    category: 'gymboree',
    description: 'Set de colchoneta con escalera para actividades motrices.',
    price: 220,
    image: '/images/products/gymboree-blanco-grande.png',
  },

  // ═══ INFLABLES ═══
  {
    id: 'bubble-house',
    name: 'Bubble House',
    category: 'inflables',
    description: '3 metros la bola x 1.80 metros túnel.',
    price: 190,
    image: '/images/products/bubble-house.png',
  },
  {
    id: 'bounce-house-blanco',
    name: 'Bounce House Blanco',
    category: 'inflables',
    description: 'Sin decoración. Dimensiones: 3.50W x 3.50L x 3.96H metros.',
    price: 120,
    image: '/images/products/bounce-house-blanco.png',
  },
  {
    id: 'inflable-grande-1',
    name: 'Inflable Grande con Tobogán',
    category: 'inflables',
    description: 'Dimensiones: 5.4 x 5 x 4 metros.',
    price: 170,
    image: '/images/products/inflable-grande-1.png',
  },
  {
    id: 'inflable-mediano',
    name: 'Inflable Mediano',
    category: 'inflables',
    description: 'Dimensiones: 4.4 x 4 x 3.8 metros.',
    price: 140,
    image: '/images/products/inflable-mediano.png',
  },
  {
    id: 'inflable-grande-2',
    name: 'Inflable Grande',
    category: 'inflables',
    description: 'Dimensiones: 5.5 x 4.5 metros.',
    price: 170,
    image: '/images/products/inflable-grande-2.png',
  },
  {
    id: 'inflable-chico',
    name: 'Inflable Pequeño',
    category: 'inflables',
    description: 'Dimensiones: 3L x 3W x 2.75H metros.',
    price: 110,
    image: '/images/products/inflable-chico.png',
  },
  {
    id: 'inflable-mini-1',
    name: 'Inflable Mini (2.7m)',
    category: 'inflables',
    description: 'Dimensiones: 2.7 x 2.2 x 2.0 metros.',
    price: 90,
    image: '/images/products/inflable-mini-1.png',
  },
  {
    id: 'inflable-mini-2',
    name: 'Inflable Mini (2.5m)',
    category: 'inflables',
    description: 'Dimensiones: 2.5 x 2.5 metros.',
    price: 90,
    image: '/images/products/inflable-mini-1.png',
  },

  // ═══ PISCINAS Y TÚNELES ═══
  {
    id: 'piscina-cuadrada-blanca',
    name: 'Piscina Cuadrada Blanca de Foam',
    category: 'piscinas',
    description: 'Colores a escoger: blanco, rosado, azul, negro. Dimensiones: 72 x 72 pulgadas.',
    price: 88,
    image: '/images/products/piscina-cuadrada-blanca.png',
  },
  {
    id: 'piscina-colores-60',
    name: 'Piscina con Colores (60")',
    category: 'piscinas',
    description: 'Dimensiones: 60 x 60 pulgadas. Varios colores disponibles.',
    price: 60,
    image: '/images/products/piscina-colores-60.png',
  },
  {
    id: 'piscina-redonda-grande',
    name: 'Piscina Redonda Grande',
    category: 'piscinas',
    description: '3 metros de diámetro.',
    price: 100,
    image: '/images/products/piscina-redonda-grande.png',
  },
  {
    id: 'piscina-redonda-chica',
    name: 'Piscina Redonda Pequeña',
    category: 'piscinas',
    description: '1.5 metros de diámetro.',
    price: 40,
    image: '/images/products/piscina-redonda-grande.png',
  },
  {
    id: 'piscina-peces',
    name: 'Piscina de Peces',
    category: 'piscinas',
    description: '1.3 metro de diámetro.',
    price: 85,
    image: '/images/products/piscina-peces.png',
  },
  {
    id: 'tunel-grande',
    name: 'Túnel Grande',
    category: 'piscinas',
    description: 'Dimensiones: 215 x 75 x 100 cm.',
    price: 50,
    image: '/images/products/tunel-grande.png',
  },
  {
    id: 'tunel-chico',
    name: 'Túnel Pequeño',
    category: 'piscinas',
    description: 'Dimensiones: 1.50 x 0.70 x 0.50 metros.',
    price: 45,
    image: '/images/products/tunel-grande.png',
  },
  {
    id: 'tunel-largo',
    name: 'Túnel Largo',
    category: 'piscinas',
    description: 'Disponible en blanco y rosado. Dimensiones: 4.26 metros de largo.',
    price: 40,
    image: '/images/products/tunel-grande.png',
  },

  // ═══ ALQUILER INDIVIDUAL ═══
  {
    id: 'surraderos-arco',
    name: '2 Surraderos y Arco',
    category: 'alquiler',
    description: '2 surraderos y arco. No incluye piscina.',
    price: 100,
    image: '/images/products/surraderos-arco.png',
  },
  {
    id: 'surradero-sencillo',
    name: 'Surradero Sencillo para Piscina',
    category: 'alquiler',
    description: 'Surradero sencillo para piscina.',
    price: 50,
    image: '/images/products/surraderos-arco.png',
  },
  {
    id: 'mini-parque',
    name: 'Mini Parque',
    category: 'alquiler',
    description: 'Mini parque blanco (70.7 x 57") o rosado (59 x 46 x 47").',
    price: 50,
    image: '/images/products/mini-parque.png',
  },
  {
    id: 'pads-piso',
    name: 'Pads de Piso',
    category: 'alquiler',
    description: 'Disponible en blanco, turquesa y rosado. Dimensiones: 5 x 5 metros.',
    price: 50,
  },
  {
    id: 'bumper-cars',
    name: 'Bumper Cars (4 carritos)',
    category: 'alquiler',
    description: 'Incluye pads, pista y 4 carritos por 3 horas con personal.',
    price: 250,
    image: '/images/products/bumper-cars.png',
    featured: true,
  },
  {
    id: 'racing-cars',
    name: 'Racing Cars',
    category: 'alquiler',
    description: 'Carritos de carrera para niños.',
    price: 75,
    image: '/images/products/racing-cars.png',
  },
  {
    id: 'caballito-saltarin',
    name: 'Caballito Saltarín',
    category: 'alquiler',
    description: 'Caballito saltarín individual.',
    price: 50,
  },
  {
    id: 'silla-bebe',
    name: 'Silla para Bebé',
    category: 'alquiler',
    description: 'Silla individual para bebé.',
    price: 2,
    maxQuantity: 20,
  },
  {
    id: 'silla-tiffany',
    name: 'Silla Tiffany',
    category: 'alquiler',
    description: 'Silla Tiffany individual.',
    price: 3,
    maxQuantity: 20,
  },
  {
    id: 'mesa-ninos',
    name: 'Mesa para Niños',
    category: 'alquiler',
    description: 'Mesa individual para niños.',
    price: 15,
    maxQuantity: 10,
  },
  {
    id: 'mesa-madera',
    name: 'Mesa de Madera',
    category: 'alquiler',
    description: 'Mesa de madera individual.',
    price: 25,
    maxQuantity: 10,
  },
  {
    id: 'lego-foam',
    name: 'Lego Foam (set)',
    category: 'alquiler',
    description: 'Set de legos de foam.',
    price: 15,
  },
  {
    id: 'roller-coaster',
    name: 'Roller Coaster',
    category: 'alquiler',
    description: 'Roller coaster individual. Disponible en blanco y rosado.',
    price: 25,
  },
  {
    id: 'cerca',
    name: 'Cerca',
    category: 'alquiler',
    description: 'Cerca individual. Disponible en blanco y rosado.',
    price: 15,
  },
  {
    id: 'palo-pinata',
    name: 'Palo de Piñata',
    category: 'alquiler',
    description: 'Palo de piñata (no incluye piñata).',
    price: 20,
  },
  {
    id: 'silla-cubo-10',
    name: 'Silla / Cubo',
    category: 'alquiler',
    description: 'Silla o cubo individual.',
    price: 10,
    maxQuantity: 20,
  },

  // ═══ SERVICIOS ═══
  {
    id: 'musica',
    name: 'Música durante el Cumpleaños',
    category: 'servicios',
    description: 'Música durante todo el evento. Duración: 3 horas.',
    price: 90,
  },
  {
    id: 'transporte',
    name: 'Transporte',
    category: 'servicios',
    description: 'Montaje y transporte ida y vuelta. Varía según ubicación.',
    price: 50,
  },
  {
    id: 'teacher-extra',
    name: 'Teacher Extra',
    category: 'servicios',
    description: 'Teacher adicional para apoyar en las actividades.',
    price: 80,
    maxQuantity: 5,
  },
  {
    id: 'animacion-modelaje',
    name: 'Animación con Modelaje y Baile',
    category: 'servicios',
    description: 'Animación con modelaje y baile (extra para planes de belleza).',
    price: 65,
  },
  {
    id: 'extra-nina-spa',
    name: 'Extra Niña (Spa)',
    category: 'servicios',
    description: 'Niña adicional para planes de belleza/spa.',
    price: 10,
    maxQuantity: 15,
  },
  {
    id: 'peinado-deluxe',
    name: 'Peinado Deluxe (Extensiones)',
    category: 'servicios',
    description: 'Peinado deluxe con extensiones de colores.',
    price: 25,
    maxQuantity: 15,
  },
  {
    id: 'maquillaje-deluxe',
    name: 'Maquillaje Deluxe (Brillantes)',
    category: 'servicios',
    description: 'Maquillaje deluxe con brillantes.',
    price: 10,
    maxQuantity: 15,
  },
  {
    id: 'facial',
    name: 'Facial',
    category: 'servicios',
    description: 'Tratamiento facial para niñas.',
    price: 10,
    maxQuantity: 15,
  },

  // ═══ MANUALIDADES ═══
  {
    id: 'magic-wand',
    name: 'Magic Wand or Sword Crafting',
    category: 'manualidades',
    description: 'Construye y decora tus varitas y espadas mágicas desde cero, agregando detalles brillantes y detalles únicos.',
    price: 0,
    image: '/images/manualidades/page2_img3.png',
  },
  {
    id: 'art-reveal',
    name: 'Art Reveal',
    category: 'manualidades',
    description: 'Pinta, raspa y descubre un arte sorpresa con la magia de tu personaje favorito.',
    price: 0,
    image: '/images/manualidades/page2_img4.png',
  },
  {
    id: 'american-girl-party',
    name: 'American Girl Party',
    category: 'manualidades',
    description: 'Peina, viste y decora a tu muñeca con artes, accesorios y peinados para horas de juego.',
    price: 0,
    image: '/images/manualidades/page2_img5.png',
  },
  {
    id: 'diy-facial-mask',
    name: 'DIY Facial Mask',
    category: 'manualidades',
    description: 'Mezcla y prepara tu propia mascarilla facial divertida y relajante.',
    price: 0,
    image: '/images/manualidades/page3_img3.png',
  },
  {
    id: 'stamp-it-up',
    name: 'Stamp It Up',
    category: 'manualidades',
    description: 'Personaliza tu maleta con serigrafía y haz que sea tan única como tú.',
    price: 0,
    image: '/images/manualidades/page3_img2.png',
  },
  {
    id: 'style-sneakers',
    name: 'Style Your Sneakers',
    category: 'manualidades',
    description: 'Diseña y transforma tus zapatillas en un accesorio lleno de estilo y personalidad.',
    price: 0,
    image: '/images/manualidades/page3_img5.png',
  },
  {
    id: 'slime-bar',
    name: 'Slime Bar',
    category: 'manualidades',
    description: 'Crea tu slime único! Elige el color, agrega un aroma divertido, mezcla la textura perfecta y decoraciones mágicas.',
    price: 0,
    image: '/images/manualidades/page4_img5.png',
  },
  {
    id: 'build-a-plush',
    name: 'Build-A-Plush',
    category: 'manualidades',
    description: 'Da vida a tu propio peluche! Rellénalo, graba un mensaje especial en su corazón, recibe su certificado y decora su casita.',
    price: 0,
    image: '/images/manualidades/page4_img6.png',
  },
  {
    id: 'squishmallow-pillows',
    name: 'Squishmallow Pillows',
    category: 'manualidades',
    description: 'Crea tu almohada squishy, suave y adorable para abrazar siempre! Personalízala con tu aroma favorito.',
    price: 0,
    image: '/images/manualidades/page4_img7.png',
  },
  {
    id: 'charm-it-up',
    name: 'Charm It Up!',
    category: 'manualidades',
    description: 'Decora espejos, lámparas, cartucheras, botellas y mucho más con whipped cream glue y montones de charms.',
    price: 0,
    image: '/images/manualidades/page5_img3.png',
  },
  {
    id: 'clay-creations',
    name: 'Clay Creations',
    category: 'manualidades',
    description: 'Moldea masilla y crea animalitos y pastelitos únicos con tus manos.',
    price: 0,
    image: '/images/manualidades/page5_img5.png',
  },
  {
    id: 'snow-globes',
    name: 'Snow Globes',
    category: 'manualidades',
    description: 'Crea tu propia bola de nieve con luz! Elige tu personaje favorito, decórala a tu estilo y llévate un recuerdo brillante.',
    price: 0,
    image: '/images/manualidades/page5_img6.png',
  },
  {
    id: 'mommy-and-me',
    name: 'Mommy & Me Sensory Play',
    category: 'manualidades',
    description: 'Actividades sensoriales y de motricidad fina basada en el tema de tu cumpleaños.',
    price: 0,
    image: '/images/manualidades/page6_img3.png',
  },
  {
    id: 'shrink-dink',
    name: 'Shrink Dink Keychains',
    category: 'manualidades',
    description: 'Dibuja, colorea y mira tu diseño encogerse mágicamente! Luego arma tu llavero único.',
    price: 0,
    image: '/images/manualidades/page6_img4.png',
  },
  {
    id: 'character-keychain',
    name: 'Character Keychain',
    category: 'manualidades',
    description: 'Elige tu personaje favorito, conviértelo en un llavero único y decóralo con tus beads favoritos.',
    price: 0,
    image: '/images/manualidades/page6_img5.png',
  },
  {
    id: 'custom-tshirt',
    name: 'Custom T-shirt Design',
    category: 'manualidades',
    description: 'Pinta y decora tu tshirt con un diseño personalizado.',
    price: 0,
    image: '/images/manualidades/page7_img3.png',
  },
  {
    id: 'unicorn-horn',
    name: 'Unicorn Horn Cones',
    category: 'manualidades',
    description: 'Decora conos mágicos de unicornio llenos de colores y fantasía!',
    price: 0,
    image: '/images/manualidades/page7_img4.png',
  },
  {
    id: 'mickey-ears',
    name: 'Mickey & Minnie Magic Ears',
    category: 'manualidades',
    description: 'Diseña tus propias orejitas mágicas con colores, brillos y accesorios para un look mágico y divertido.',
    price: 0,
    image: '/images/manualidades/page7_img5.png',
  },
  {
    id: 'patch-sparkle',
    name: 'Patch & Sparkle',
    category: 'manualidades',
    description: 'Decora lazos, kippot, maletas, libretas y monederos con parches y estilo único!',
    price: 0,
    image: '/images/manualidades/page8_img3.png',
  },
  {
    id: 'apron-art',
    name: 'Apron Art',
    category: 'manualidades',
    description: 'Personaliza tu delantal con colores, brillos y tu estilo único para divertirte mientras cocinas.',
    price: 0,
    image: '/images/manualidades/page8_img4.png',
  },
  {
    id: 'cupcake-decorating',
    name: 'Cupcake & Cake Decorating',
    category: 'manualidades',
    description: 'Crea tu propia pizza, decora cupcakes o haz tu fruit kebab. Diversión y sabor en cada creación!',
    price: 0,
    image: '/images/manualidades/page8_img5.png',
  },
  {
    id: 'magic-lab',
    name: 'Magic Lab',
    category: 'manualidades',
    description: 'Ciencia mágica para niños con experimentos sorprendentes que despiertan la curiosidad.',
    price: 0,
    image: '/images/manualidades/page9_img3.png',
  },
  {
    id: 'potion-necklace',
    name: 'Potion Necklace',
    category: 'manualidades',
    description: 'Los niños mezclan líquidos de colores brillantes en pequeños frascos para crear un collar único en forma de poción mágica.',
    price: 0,
    image: '/images/manualidades/page9_img4.png',
  },
  {
    id: 'sand-bottles',
    name: 'Sand Bottles',
    category: 'manualidades',
    description: 'Llena botellitas con arena de colores mágicos y crea un recuerdo brillante y especial!',
    price: 0,
    image: '/images/manualidades/page9_img5.png',
  },
  {
    id: 'glitter-bottles',
    name: 'Glitter Bottles',
    category: 'manualidades',
    description: 'Botellas para rellenar con escarcha y decorarla con tus stickers favoritos.',
    price: 0,
    image: '/images/manualidades/page10_img3.png',
  },
  {
    id: 'lava-lamp',
    name: 'Lava Lamp',
    category: 'manualidades',
    description: 'Haz tu propia lámpara de lava y observa cómo la magia cobra vida con burbujas de colores.',
    price: 0,
    image: '/images/manualidades/page10_img4.png',
  },
  {
    id: 'holiday-crafts',
    name: 'Holiday Crafts',
    category: 'manualidades',
    description: 'Personaliza tu gorro de navidad con tu nombre, diseños de santa y mucho brillo.',
    price: 0,
    image: '/images/manualidades/page10_img5.png',
  },
  {
    id: 'rhinestone-sparkle',
    name: 'Sparkle & Shine with Rhinestone',
    category: 'manualidades',
    description: 'Personaliza con rhinestones de colores y crea un diseño único que refleje tu estilo.',
    price: 0,
    image: '/images/manualidades/page11_img3.png',
  },
  {
    id: 'bucket-hat',
    name: 'Design Your Own Bucket Hat',
    category: 'manualidades',
    description: 'Decora tu sombrero a tu estilo! Con pintura para tela, parches, pins y mucho color.',
    price: 0,
    image: '/images/manualidades/page11_img4.png',
  },
];
