// Auto-generated cross-sell rules based on category logic + real order signals.
// Edit from Admin > Catálogo > Productos (per product) to override.
export const DEFAULT_CROSS_SELL_RULES: Record<string, string[]> = {
  "silla-bebe": ["algodon-azucar", "slushy", "mesa-ninos", "palo-pinata", "custom-1775418746202"],
  "mesa-ninos": ["algodon-azucar", "slushy", "silla-bebe", "palo-pinata", "custom-1775418746202"],
  "bumper-cars": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "custom-1775418686748": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "racing-cars": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "custom-1775418733523": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "custom-1775418746202": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "custom-1775373043752": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "palo-pinata": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "custom-1775418746202"],
  "custom-1775373083876": ["algodon-azucar", "slushy", "silla-bebe", "mesa-ninos", "palo-pinata"],
  "bubble-house": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "bounce-house-blanco": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-grande-1": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-mediano": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-grande-2": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-chico": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-mini-1": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "inflable-mini-2": ["caballito-saltarin", "lego-foam", "silla-bebe", "slushy"],
  "magic-wand": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "art-reveal": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "american-girl-party": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "diy-facial-mask": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "stamp-it-up": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "style-sneakers": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "slime-bar": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "build-a-plush": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "squishmallow-pillows": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "charm-it-up": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "clay-creations": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "snow-globes": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "mommy-and-me": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "shrink-dink": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "character-keychain": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "custom-tshirt": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "unicorn-horn": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "mickey-ears": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "patch-sparkle": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "apron-art": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "cupcake-decorating": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "magic-lab": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "potion-necklace": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "sand-bottles": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "glitter-bottles": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "lava-lamp": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "holiday-crafts": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "rhinestone-sparkle": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "bucket-hat": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "prod-1775835048649": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "custom-1775422201729": ["mesa-ninos", "silla-bebe", "algodon-azucar", "slushy", "palo-pinata"],
  "plan-1": ["algodon-azucar", "slushy", "silla-bebe", "palo-pinata", "mesa-ninos"],
  "plan-2": ["algodon-azucar", "slushy", "silla-bebe", "palo-pinata", "mesa-ninos"],
  "plan-3": ["algodon-azucar", "slushy", "silla-bebe", "palo-pinata", "mesa-ninos"],
  "plan-12": ["algodon-azucar", "slushy", "silla-bebe", "palo-pinata", "mesa-ninos"],
  "show-titeres": ["slushy", "silla-bebe", "mesa-ninos", "algodon-azucar", "palo-pinata"],
  "animacion": ["silla-bebe", "mesa-ninos", "slushy", "algodon-azucar", "palo-pinata"],
  "personaje-animacion": ["silla-bebe", "mesa-ninos", "slushy", "algodon-azucar", "palo-pinata"],
  "algodon-azucar": ["popcorn", "raspado", "mesa-ninos", "silla-bebe", "palo-pinata"],
  "algodon-automatico": ["algodon-azucar", "popcorn", "mesa-ninos", "silla-bebe", "palo-pinata"],
  "raspado": ["algodon-azucar", "popcorn", "mesa-ninos", "silla-bebe", "palo-pinata"],
  "popcorn": ["algodon-azucar", "raspado", "mesa-ninos", "silla-bebe", "palo-pinata"],
  "slushy": ["algodon-azucar", "popcorn", "mesa-ninos", "silla-bebe", "palo-pinata"],
  "gymboree-blanco-grande": ["inflable-mini-1", "silla-bebe", "slushy"],
  "gymboree-rosado-grande": ["inflable-mini-1", "silla-bebe", "slushy"],
  "custom-1774442281003": ["inflable-mini-1", "silla-bebe", "slushy"],
  "piscina-bolas": ["inflable-mini-1", "silla-bebe", "slushy"],
  "surraderos-arco": ["inflable-mini-1", "silla-bebe", "slushy"],
  "mini-parque": ["inflable-mini-1", "silla-bebe", "slushy"],
  "set-colchoneta-escalera": ["inflable-mini-1", "silla-bebe", "slushy"],
  "pads-piso": ["inflable-mini-1", "silla-bebe", "slushy"],
  "tunel": ["inflable-mini-1", "silla-bebe", "slushy"],
  "caballito-saltarin": ["inflable-mini-1", "silla-bebe", "slushy"],
  "lego-foam": ["inflable-mini-1", "silla-bebe", "slushy"],
  "roller-coaster": ["inflable-mini-1", "silla-bebe", "slushy"],
  "custom-1775418666250": ["inflable-mini-1", "silla-bebe", "slushy"],
  "prod-1775974133500": ["inflable-mini-1", "silla-bebe", "slushy"],
  "prod-1775974106416": ["inflable-mini-1", "silla-bebe", "slushy"],
  "cerca": ["inflable-mini-1", "silla-bebe", "slushy"],
  "plan-6-makeup": ["silla-bebe", "mesa-ninos", "algodon-azucar", "slushy", "palo-pinata"],
  "plan-7-manicure": ["silla-bebe", "mesa-ninos", "algodon-azucar", "slushy", "palo-pinata"],
  "plan-9-hair": ["silla-bebe", "mesa-ninos", "algodon-azucar", "slushy", "palo-pinata"],
  "plan-10-spa": ["silla-bebe", "mesa-ninos", "algodon-azucar", "slushy", "palo-pinata"],
  "plan-11-princess": ["silla-bebe", "mesa-ninos", "algodon-azucar", "slushy", "palo-pinata"],
};
